site_name: Gamma Config
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Nunito Sans
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.tracking

plugins:
  - mkdocstrings
  - gen-files:
      scripts:
        - docs/gen_api.py #
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition

nav:
  - Home: README.md

  - "User Guide":
      - Writing configuration files: writing-config.md
      - Using gamma-config: using.md
      - Environment specific config: environment.md
      - Built-in tags: built-in-tags.md
      - Custom tags: custom-tags.md

  - "How-to":
      - "Structured configuration": structured.md

  - "Advanced":
      - Multiple dispatch: multi-dispatch.md
      - API Reference: api/
