site_name: Gamma Config
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Nunito Sans
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition


nav:
  - Home: README.md
  
  - "User Guide":
    - Writing configuration files: writing-config.md
    - Using gamma-config: using.md
    - Environment specific config: environment.md
    - Built-in and custom tags: tags.md
  
  - "How-to":
    - "Structured configuration": structured.md 
  
  - "Advanced":
    - Multiple dispatch: multi-dispatch.md
    - API Reference: api.md
