# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}-{{ checksum "build-requirements.txt" }}
            - v1-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r build-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "build-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=$PWD
            pytest --junitxml=test-results/junit.xml --cov-report xml --cov=gamma test/

      - store_test_results:
          path: test-results

  doc:
    docker:
      - image: circleci/python:3.6.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}-{{ checksum "build-requirements.txt" }}
            - v1-
      - run:
          name: install nodejs
          command: |
            NODE_VER=v14.15.4
            mkdir bin
            wget https://nodejs.org/dist/$NODE_VER/node-$NODE_VER-linux-x64.tar.xz
            tar xf node-${NODE_VER}-linux-x64.tar.xz
            sudo ln -s $PWD/node-${NODE_VER}-linux-x64/bin/node /usr/local/bin
            sudo ln -s $PWD/node-${NODE_VER}-linux-x64/bin/npm /usr/local/bin

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            cd docs
            make html

      - run:
          name: push docs
          command: |
            git config user.email "almeida.cloves@bcg.com"
            git config user.name "Cloves Almeida"
            npm install -g gh-pages@2.0.1
            gh-pages -d docs/_build/html -t -r https://$github_pat@github.gamma.bcg.com/bcg/gamma-config.git

workflows:
  version: 2
  build_and_test_publish:
    jobs:
      - build
      - doc:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/

      - publish:
          requires:
            - doc
          filters:
            tags:
              only: /^v.*/
