# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}-{{ checksum "build-requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r build-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "build-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=$PWD
            pytest --junitxml=test-results/junit.xml --cov-report xml --cov=gamma test/

      - store_test_results:
          path: test-results

