####
# Meta parameters for configuring the gamma-config tool itself. This file must be
# named '00-meta.yaml'.
#
# The configuration here is loaded *and evaluated* before any other configuration
# file, so you're not able to use expressions that references other configs here.
####

# Extra folders to load. By default we include a relative folder dynamically set
# by the 'ENVIRONMENT' environment. variable
include_folders:
  - !env ENVIRONMENT|__unset__

# List the names of any tag you want to disble in the configuration.
# Note that all tags are enabled during for the 'meta' config.
blacklist_tags:
    # - "!expr"         # Python expressions
    # - "!ref"          # Config self referencing
    # - "!env"          # References environment variables
    # - "!env_secret"   # References secret environment variables
