name: Build
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  Build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: create venv
        run: python -m venv .venv

      - name: install requirements
        run: |
          . .venv/bin/activate
          make install

      - name: build / run tests
        run: |
          . .venv/bin/activate
          export PYTHONPATH=$PWD
          make build
          make test

      - name: archive whl
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/*.whl

      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: Github Actions
          GIT_AUTHOR_EMAIL: noreply@github.gamma.bcg.com
        run: |
          . .venv/bin/activate
          export PYTHONPATH=$PWD
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.gamma.bcg.com/${GITHUB_REPOSITORY}.git
          make publish-docs

  Publish:
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/download-artifact@master
        with:
          name: dist

      - name: Publish docs
        run: |
          . .venv/bin/activate
          export PYTHONPATH=$PWD
          make publish
