name: Build
on:
  push:
    branches:
      - master
      - feat/pdm
    tags:
      - v*

jobs:
  Build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: Create venv
        run: python -m venv .venv

      - name: install requirements
        run: |
          curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
          . .venv/bin/activate
          pdm install --dev

      - name: Build / run tests
        run: |
          . .venv/bin/activate
          export PYTHONPATH=$PWD
          make build
          make lint
          make test

      - name: Archive whl
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/*.whl

      - name: Check archives
        run: |
          . .venv/bin/activate
          twine check dist/*

      - name: Build docs
        run: |
          . .venv/bin/activate
          export PYTHONPATH=$PWD
          make docs

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  Publish:
    environment: pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: Build
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: create venv and install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install twine

      - name: Publish to GH and PyPI
        env:
          GH_HOST: github.gamma.bcg.com
          GH_ENTERPRISE_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          PYPY_TOKEN: ${{ secrets.PYPY_TOKEN }}
          GH_DEBUG: 1
        run: |
          . .venv/bin/activate
          twine check dist/*
          gh release create $GITHUB_REF_NAME --repo $GITHUB_REPOSITORY --notes "New release $GITHUB_REF_NAME" dist/*
          twine upload --verbose -u __token__ -p "$PYPY_TOKEN" dist/*
